SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE history;
TRUNCATE TABLE book_genres;
TRUNCATE TABLE genres;
TRUNCATE TABLE books;
TRUNCATE TABLE locations;
TRUNCATE TABLE purchasers;
TRUNCATE TABLE publishers;
TRUNCATE TABLE authors;
SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE authors AUTO_INCREMENT = 1;
ALTER TABLE publishers AUTO_INCREMENT = 1;
ALTER TABLE locations AUTO_INCREMENT = 1;
ALTER TABLE books AUTO_INCREMENT = 1;
ALTER TABLE genres AUTO_INCREMENT = 1;
ALTER TABLE history AUTO_INCREMENT = 1;
