DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS book_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS purchasers;
DROP TABLE IF EXISTS publishers;
DROP TABLE IF EXISTS authors;